site:
  title: InspectIT Ocelot
  start_page: ocelot-configserver::index.adoc
content:
  sources:
  - url: https://github.com/Napfschnecke/inspectit-ocelot.git
    branches: concept/ascii-ssg-folders
    start_paths: docs/*/*
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
